doctrine:
    dbal:
        # configure these for your database server
        # use postgresql for PostgreSQL
        # use sqlite for SQLite
        driver: 'mysql'
        server_version: '5.7'

        # only needed for MySQL
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            default:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'Entity'
                # this is alias for dql;
                # alias: 'Abc' - select a from Abc:About a
                # ./bin/console doctrine:query:dql "select a from Abc:About a" --env=test --em=default
                # or refer to the entities in your DQL by their namespaces;
                # namespaces can be set in composer.json
                alias: 'Entity'
           #  gedmo_translatable:
           #      type: annotation
           #      prefix: Gedmo\Translatable\Entity
           #      dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
           #      alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
           #      is_bundle: false
           #  gedmo_translator:
           #      type: annotation
           #      prefix: Gedmo\Translator\Entity
           #      dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
           #      alias: GedmoTranslator # (optional) it will default to the name set for the mapping
           #      is_bundle: false
           # gedmo_loggable:
           #     type: annotation
           #     prefix: Gedmo\Loggable\Entity
           #     dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
           #     alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
           #     is_bundle: false
           #  gedmo_tree:
           #      type: annotation
           #      prefix: Gedmo\Tree\Entity
           #      dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
           #      alias: GedmoTree # (optional) it will default to the name set for the mapping
           #      is_bundle: false
